# Basic
name:               "Alexander Myltsev"
title:              "Alexander Myltsev"

author:
  github:           alexander-myltsev
  linkedin:         alexandermyltsev
  twitter:          Alex_Myltsev
  email:            alex<at>myltsev<dot>com

copyright:
  year:             2019
  name:             Alexander Myltsev

# Google-analytics
google-analytics:
  id:               UA-63953015-1

# Disqus
disqus:
  id:               "y-code"

# URL
url:                "http://myltsev.com"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Moscow
permalink:          /:year/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM
  # syntax_highlighter: rouge
  hard_wrap: false

# Navigation
nav:
  - name:           "CV"
    url:            "/myltsev-cv.pdf"
  - name:           "Github"
    url:            "https://github.com/alexander-myltsev"
  # - name:           "About"
  #   url:            "/about"
  - name:           "Tags"
    url:            "/tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

exclude: [vendor, "less", "node_modules", "Gruntfile.js", "package.json", "README.md", "Gemfile", "Gemfile.lock"]
