# Site settings
title: ???
header-img: img/home-bg.jpg
email: alex@myltsev.name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://myltsev.name"
twitter_username: Alex_Myltsev
github_username: alexander-myltsev
facebook_username: alexander.myltsev

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
