# Site settings
title: y-code
header-img: img/home-bg.jpg
description: "Blog about things I am mostly interested in code: functional programming, parsing grammars, compilers"
baseurl: "/"
url: "http://myltsev.com"
author:
  name: 'Alexander Myltsev'
  email: alex@myltsev.com
  twitter_username: Alex_Myltsev
  github_username: alexander-myltsev
  disqus_shortname: y-code
  google_tracking_id: UA-63953015-1

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: /:year/:title
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "Gemfile", "Gemfile.lock"]

kramdown:
  input: GFM
  # syntax_highlighter: rouge
  hard_wrap: false
